// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDqIcJW_P1jdbXan56cJ2ku94v1cqrr8PU',
    appId: '1:173583299191:web:243857d0377fc61b968c72',
    messagingSenderId: '173583299191',
    projectId: 'multiservicios-4623c',
    authDomain: 'multiservicios-4623c.firebaseapp.com',
    storageBucket: 'multiservicios-4623c.appspot.com',
    measurementId: 'G-Q3RDHBZWCC',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBjl_Xl-YHCZLOxDqpkw8ZYxKkg5i21S-k',
    appId: '1:173583299191:android:56dcfe7fed226bfd968c72',
    messagingSenderId: '173583299191',
    projectId: 'multiservicios-4623c',
    storageBucket: 'multiservicios-4623c.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD4onLWXT3iADorlSFhA5E-rjoBDlg8DJ8',
    appId: '1:173583299191:ios:d568a74768c67299968c72',
    messagingSenderId: '173583299191',
    projectId: 'multiservicios-4623c',
    storageBucket: 'multiservicios-4623c.appspot.com',
    iosBundleId: 'com.example.multiservicesApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD4onLWXT3iADorlSFhA5E-rjoBDlg8DJ8',
    appId: '1:173583299191:ios:d568a74768c67299968c72',
    messagingSenderId: '173583299191',
    projectId: 'multiservicios-4623c',
    storageBucket: 'multiservicios-4623c.appspot.com',
    iosBundleId: 'com.example.multiservicesApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDqIcJW_P1jdbXan56cJ2ku94v1cqrr8PU',
    appId: '1:173583299191:web:673f893435116683968c72',
    messagingSenderId: '173583299191',
    projectId: 'multiservicios-4623c',
    authDomain: 'multiservicios-4623c.firebaseapp.com',
    storageBucket: 'multiservicios-4623c.appspot.com',
    measurementId: 'G-XDYXEG9WG7',
  );

}